### PR TITLE
Update document about Conditional counter cache

### PR DESCRIPTION
**Pull request by ykamez**
Thanks for creating this gem! It's super useful!

---

I ran into a problem referenced in https://github.com/magnusvk/counter_culture/issues/96, so I updated documentation.
Please take a look at it.

### CODE REVIEW

**Comment by magnusvk** [comment]
Thank you—however, as it stands your change isn't quite accurate. Providing `column_names` is optional and only required if you want to use `counter_culture_fix_counts`. Also, there already exists documentation on this: https://github.com/magnusvk/counter_culture#handling-dynamic-column-names

Perhaps we can just provide a link to the ☝️ existing documentation, along the lines of "if you would like to use this with `counter_culture_fix_counts` make sure to also provide the `column_names` configuration." Would that have been helpful?

**Comment by ykamez** [comment]
Thank you for your response!

> Thank you—however, as it stands your change isn't quite accurate. Providing `column_names` is optional and only required if you want to use `counter_culture_fix_counts`. Also, there already exists documentation on this: https://github.com/magnusvk/counter_culture#handling-dynamic-column-names


Right.

> Perhaps we can just provide a link to the ☝️ existing documentation, along the lines of "if you would like to use this with `counter_culture_fix_counts` make sure to also provide the `column_names` configuration." Would that have been helpful?

It sounds good. I'll add the lines and the link.

**Review by magnusvk — APPROVED** [review]
Thank you!

**Comment by ykamez** [comment]
Thank you!

**Pull request merged**
