### PR TITLE
Implement specific increment/decrement counter methods

### PR DESCRIPTION
**Pull request by adzap**
I found the change_counter_cache is a little too open for a public method so I implemented AR-style increment/decrement methods which is more intentional and less error prone.

Also a typo fix, spec fix, and moved an option validation into the counter class in this PR as well, because I am crap at pull requests.

### CODE REVIEW

**Comment by magnusvk** [comment]
Something went wrong with the diff here; this has conflicts.

**Comment by magnusvk** [comment]
Instead of making these new methods, shouldn't we just make that method private? What's the point of having a public method for this in the first place?

**Comment by adzap** [comment]
The methods need to be public to able to call them from the AR extension, and are the logical public interface to a counter.

Separate methods with a clearer and constrained use is optimal, as you are only doing one or the other. Calling the old update method directly could have had accidental increment without the option passed to control the operation. Things like that irk me.

Where is the conflict?

**Comment by magnusvk** [comment]
screenshot 2016-05-09 10 00 10
Merge conflicts.

**Comment by magnusvk** [comment]
Closing this for lack of activity.

**Pull request closed without merging**
