### PR TITLE
Fix Rails version check in migration generator (Fixes #280)

### LINKED ISSUE #280: migration not Rails version aware
the generator creates a migration with the old-style Migration class `ActiveRecord::Migration`

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
```

I think there's a way to pipe the Rails version into the template as it is being generated 

I did it in another gem like this
```
class CreateUniversalTrackManagerTables < ActiveRecord::Migration<%= migration_version %>
  def self.up
    ActiveRecord::Base.transaction do

```

### PR DESCRIPTION
**Pull request by magnusvk**
To include the Rails version not just for Rails 5.x but also future
versions.

### CODE REVIEW

**Comment by jasonfb** [comment]
testing now

**Comment by jasonfb** [comment]
works as expected. when I use this fix branch of this gem, the generator correctly generates a AR migration that has the version number

I tested just using the example in the README

```
MBA-gold:test-fix-rails-version-check-in-migration-test jason$ rails generate counter_culture Category products_count
Running via Spring preloader in process 92724
      create  db/migrate/20200517134855_add_products_count_to_categories.rb
```

Gemfile — test-fix-rails-version-check-in-migration-test 2020-05-17 09-51-21


20200517134855_add_products_count_to_categories rb — test-fix-rails-version-check-in-migration-test 2020-05-17 09-51-05

**Comment by jasonfb** [comment]
that would be a 👍

**Comment by magnusvk** [comment]
Thanks @jasonfb—fix released as 2.5.1.

**Pull request merged**
