### PR TITLE
Allow updating of timestamps when fixing counts

### PR DESCRIPTION
**Pull request by AlexVPopov**
As discussed in #210, I'm opening a PR to allow updating of timestamps for `counter_culture_fix_counts`. I appreciate your feedback.

### CODE REVIEW

**Comment by magnusvk** [comment]
@AlexVPopov this looks great, thank you! Sorry for the slow turnaround on review.

Just two things:
1. Can you rebase / merge in latest master to get rid of that test failure?
2. Can you add a test to make sure the timestamps don't change when `touch` isn't passed?

Thanks again!

**Comment by AlexVPopov** [comment]
@magnusvk I rebased on master. Sure, it is no problem for me to add the test you mentioned, but I think that the the first test I added already covers this:

```ruby
...
Review.counter_culture_fix_counts(skip_unsupported: true, only: :user)
Review.counter_culture_fix_counts(skip_unsupported: true, only: :product, touch: true)
...
expect(user.updated_at).to eq old_user_updated_at
expect(product.updated_at).to be > old_product_updated_at
...
```

If you still think it makes sense, I'll add a separate test for this.

**Comment by AlexVPopov** [comment]
Hey @magnusvk No problem, I agree it's nicer to have two tests about that. PR updated.

By the way, would you have accepted the following:

```ruby
Timecop.travel(1.second.from_now) do
  Review.counter_culture_fix_counts(skip_unsupported: true, only: :product, touch: true)

  expect { product.reload }.to change { product.updated_at }
end
```
?

On the one hand, it does not assert that the new `updated_at` is after the old one, but on the other hand, it makes assigning `old_product_updated_at` redundant and reads better IMO.

**Comment by magnusvk** [comment]
@AlexVPopov thank you, merged. I think I prefer the current test where it explicitly asserts that it's later, but yeah ^^ that also would have worked.

**Comment by magnusvk** [comment]
@AlexVPopov released as 1.10.0. Thanks again!

**Comment by AlexVPopov** [comment]
@magnusvk Glad I could contribute.

**Pull request merged**
