### PR TITLE
Fixes: #30 | Add support for joining tables while fixing_counts(Model#counter_culture_fix_counts)

### PR DESCRIPTION
**Pull request by swapab**
@magnusvk That's pretty much I had thought about.

I feel the `CounterCulture::Reconciler` class can be further abstracted out to be more `CounterCulture::Join` specific. Thoughts?

### CODE REVIEW

**Comment by swapnilabnave** [comment]
Any word on this one ?

**Comment by magnusvk** [comment]
Sorry, was AFK for a bit. Just getting back to this.

Thinking about this some more: Is there a way to make this automatic instead? It rankles me a bit that one still has to specify two options here. What if `column_names` supported a hash for this. As an example:
```ruby
:column_names => {
    ["products.product_type = ?", 'awesome'] => 'awesome_count',
    ["products.product_type = ?", 'sucky'] => 'sucky_count'
```
would become
```ruby
:column_names => {
    [{ products: :product_type }, 'awesome'] => 'awesome_count',
    [{ products: :product_type }, 'sucky'] => 'sucky_count'
```

This looks like a better way to pass these options anyhow, looking at this today. And it would allow us to automatically infer if another join is necessary here?

Or am I overthinking this?

**Comment by swapnilabnave** [comment]
Hash looks better. I'll make the change soon.

**Comment by magnusvk** [comment]
@swapnilabnave Any news on this?

**Comment by swapnilabnave** [comment]
@magnusvk It went out of my radius.
I'll update the patch soon.

**Comment by swapnilabnave** [comment]
@magnusvk 
I actually have a question.

If we are allowing the hash structure of `column_names` option, then the SQL conditions such as `IN` won't be useful.

For example: following query can't be defined or recognized in hash syntax.

`"products.product_type IN (?)", ['awesome', 'superb']`

```ruby
:column_names => {
    [{ products: :product_type }, 'awesome'] => 'awesome_count',
    [{ products: :product_type }, 'sucky'] => 'sucky_count'
```
--
To keep the current syntax and make the joins 'automatic', can we instantiate the `@joins` variable based on the conditions those are being defined on `column_names`. So if the conditional table is different then the applied model's table then we join that table else we don't.

_I can code this if my words sounds confusing._

**Comment by swapnilabnave** [comment]
@magnusvk 
This is complete from my side. Can you please review ?

**Comment by magnusvk** [comment]
Hm; we can do the `IN` automatically based on the object type, right? If it's an `Array` (or `Enumerable`, really) then we use `IN`, if not we use `=`. Just like how `where()` works in ActiveRecord. Am I missing something?

**Comment by krim** [comment]
Hello. I need "joins" functional too. What's wrong with this PR?

**Comment by shaneog** [comment]
I think @swapab needs to rebase this to fix the conflicts for @magnusvk to consider it.

**Comment by magnusvk** [comment]
Yeah unfortunately looks like this PR may be abandoned at this point...

**Comment by magnusvk** [comment]
Closing this, feel free to reopen if there's progress on this work.

**Comment by olivierlacan** [comment]
Aside from a rebase, what would you want for this PR to be complete @magnusvk?

**Comment by magnusvk** [comment]
See this comment for changes I was still hoping for here:
https://github.com/magnusvk/counter_culture/pull/138#issuecomment-231856739

I'd still be willing to consider this change or one like it if you wanted to pick up the work.

**Pull request closed without merging**
