### PR TITLE
Add Ruby 3.1 to CI

### PR DESCRIPTION
**Pull request by petergoldstein**
Adds Ruby 3.1 to the CI matrix.  I used an include approach as that required the least change.

### CODE REVIEW

**Comment by magnusvk** [comment]
Thank you—why only test against Rails 7 though? [Sounds as if Rails 6.1 should also be compatible.](https://discuss.rubyonrails.org/t/is-rails-6-1-x-compatible-with-ruby-3-1/79713/6)

**Comment by petergoldstein** [comment]
@magnusvk There's some debate about whether Rails 6.1 is compatible with Ruby 3.1.  But most things seem to work.

That said, to get it to work generally requires a modification to the Rails 6.1 Gemfile.  We need to conditionally include the `net/smtp', 'net/pop', and 'net/imap' gems when the Ruby version is 3.1 or greater.   If you want me to add that let me know and I can make the necessary modifications.

**Comment by petergoldstein** [comment]
@magnusvk Please let me know how you want to resolve the above comment.  I can add Rails 6.1 with the Ruby 3.1+ hackery in the rails_6_1.gemfile or just leave it as is.  And if there's anything else required to get this merged, please let me know.

**Comment by petergoldstein** [comment]
@magnusvk Anything I can do to move this forward?  Thanks.

**Comment by magnusvk** [comment]
Sorry for the radio silence, I just tried this in #357 and it worked fine without extra changes. Thanks for the contribution!

**Pull request closed without merging**
