### PR TITLE
Refactor Reconciler; Reconciliation

### PR DESCRIPTION
**Pull request by reidab**
Along the way to figuring out #254, I thought I was going to need much more access to the internal state of `Reconciler::Reconciliation#join_clauses` to fix things. To get there, I ended up teasing `join_clauses` apart to use a much more object-oriented approach, introducing a `RelationJoin` object to handle all of the internal state for each join. 

It's kind of a huge refactor, so I totally understand if you're not interested, but since I had this code just sitting here I cleaned it up and submitted a PR. I think it makes the reconciliation process a bit easier to reason about, but the added abstraction may not be desired. 😁

### CODE REVIEW

**Comment by magnusvk** [comment]
@reidab I like this quite a bit, thank you. Could you make this mergable again based off your other PR's changes? I think I'll want to merge this.

**Comment by reidab** [comment]
Rebased this on the current `master`

**Comment by magnusvk** [comment]
@reidab it looks like I never looked at your rebase, I'm sorry about that. Is this refactor still something you're interested in getting merged?

**Comment by magnusvk** [comment]
Closing since it's inactive.

**Pull request closed without merging**
