### PR TITLE
Support Discard for soft-deletes

### PR DESCRIPTION
**Pull request by reidab**
This adds support for properly counting things when using the [Discard](https://github.com/jhawthorn/discard) gem for soft deletes.

### CODE REVIEW

**Comment by jhawthorn** [comment]
I'm not sure this makes sense unless a `default_scope` is used (which isn't default or recommended).

**Comment by reidab** [comment]
Can you elaborate? I added this patch specifically because I didn't want to use `default_scope` with Discard.

As near as I can tell, this works fine without the default scope by:

- decrementing the count `before_discard`
- incrementing it `before_undiscard`
- filtering on records where the `discard_column` is not null when reconciling counts

**Comment by magnusvk** [comment]
@reidab this makes sense to me; a soft-deleted model should still decrement the count. Released as 1.12.0. Thanks for your contribution!

Also @jhawthorn 👋 — small world!

**Comment by jhawthorn** [comment]
:wave: :heart: @magnusvk Hope you're doing well!

**Pull request merged**
