### PR TITLE
add better support of paranoia gem

### PR DESCRIPTION
**Pull request by epoberezhny**

### CODE REVIEW

**Comment by magnusvk** [comment]
Thank you for this @epoberezhny — can you provide some more background on this, though? I don't quite understand the issue this is addressing yet.

**Comment by epoberezhny** [comment]
Thank you for response! Earlier if we caused the destroying on the same record more than once with paranoia gem, the counter changed more than once too.

**Comment by magnusvk** [comment]
@epoberezhny thank you!

**Comment by magnusvk** [comment]
@epoberezhny just released this as 1.9.2

**Comment by epoberezhny** [comment]
Cool, thanks @magnusvk! I also noticed that it can be used without the `model` argument in lambdas if you want a more compact code.

**Pull request merged**
